<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle($this->translate('Meg Cady Photography'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/flat-ui.css')
                        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap-responsive.css')
                        ->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.css') 
                        ->prependStylesheet($this->basePath() . '/css/style.css') ?>
                        

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',)) ?>
                                      
		<?php $this->inlineScript()->prependFile($this->basePath() . '/js/jquery-ui-1.10.3.custom.min.js')
								   ->prependFile($this->basePath() . '/js/jquery.ui.touch-punch.min.js')
								   ->prependFile($this->basePath() . '/js/bootstrap.min.js')
								   ->prependFile($this->basePath() . '/js/bootstrap-select.js')
								   ->prependFile($this->basePath() . '/js/bootstrap-switch.js')
								   ->prependFile($this->basePath() . '/js/flatui-checkbox.js')
								   ->prependFile($this->basePath() . '/js/flatui-radio.js')
								   ->prependFile($this->basePath() . '/js/jquery.tagsinput.js')
								   ->prependFile($this->basePath() . '/js/jquery.placeholder.js')
								   ->prependFile($this->basePath() . '/js/jquery.stacktable.js') 
								   ->prependFile($this->basePath() . '/js/jquery-1.8.3.min.js') ?>
    </head>
    <body>
        
        <div class="navbar navbar-fixed-top">
        
			<div class="navbar-inner">
			  	<div class="container">
			  	
			    	<button type="button" class="btn btn-navbar" data-toggle="collapse" data-target="#nav-collapse-02"></button>
			    	
					<a href="#fakelink" class="brand fui-flat"></a>
					
					<div class="nav-collapse collapse" id="nav-collapse-02">
					
						<form class="navbar-search form-search pull-right" action="">
							<div class="input-append">
								<input type="text" class="search-query span2" placeholder="Search">
								<button type="submit" class="btn btn-large">
									<i class="fui-search"></i>
								</button>
							</div>
						</form>
			
						<ul class="nav pull-right">
							<li class="active">
								<a href="#fakelink">
									<span class="fui-user"></span><span class="hidden-desktop">My Account</span>
								</a>
							</li>
							<li>
								<a href="#fakelink">
					            	<span class="fui-mail"></span><span class="hidden-desktop">Messages</span>
									<span class="navbar-new">1</span>
								</a>
							</li>
							<li>
								<a href="#fakelink">
									<span class="fui-gear"></span><span class="hidden-desktop">Settings</span>
								</a>
							</li>
						</ul> <!-- /nav -->
						
					</div><!--/.nav-collapse -->
				</div>
			</div>
		</div> <!-- /navbar -->

		<div class="container">
			<div class="iconbar iconbar-success">
				<ul>
					<li><a href="#fakelink" class="fui-user"></a></li>
					<li class="active"><a href="#fakelink" class="fui-calendar"></a></li>
					<li><a href="#fakelink" class="fui-chat"></a></li>
					<li><a href="#fakelink" class="fui-mail"></a></li>
					<li>
						<a href="#fakelink" class="fui-gear">
						  	<span class="iconbar-unread">1</span>
						</a>
					</li>
				</ul>
			</div> <!-- /iconbar -->
		</div>
		
        <div class="container">
            <?php echo $this->content; ?>
        </div> <!-- /container -->
            
		<div class="bottom-menu">
			<div class="container">
				<div class="row">
					<div class="span2 brand">
						<a href="#fakelink" class="fui-flat"></a>
					</div>
			
					<div class="span8">
				    	<ul class="bottom-links">
							<li><a href="#fakelink">About Us</a></li>
							<li><a href="#fakelink">Store</a></li>
							<li class="active"><a href="#fakelink">Jobs</a></li>
							<li><a href="#fakelink">Privacy</a></li>
							<li><a href="#fakelink">Terms</a></li>
							<li><a href="#fakelink">Follow Us</a></li>
							<li><a href="#fakelink">Support</a></li>
							<li><a href="#fakelink">Links</a></li>
						</ul>
					</div>
				
					<div class="span2">
						<ul class="bottom-icons">
						  <li><a href="#fakelink" class="fui-pinterest"></a></li>
						  <li><a href="#fakelink" class="fui-facebook"></a></li>
						  <li><a href="#fakelink" class="fui-twitter"></a></li>
						</ul>
					</div>
				</div>
			</div>
		</div> <!-- /bottom-menu -->
        
        <?php echo $this->inlineScript() ?>
    </body>
</html>
